cat << 'EOF' > build_eric_site.sh
#!/bin/bash

echo "🚀 Generating Enhanced Academic Portal for Eric (Expanded Content)..."
mkdir -p css

# 1. CSS (维持精美外观)
cat << 'CSS_EOF' > css/style.css
:root { --emerald-dark: #022c22; --emerald-main: #064e3b; --emerald-light: #10b981; --paper-bg: #faf9f6; --text-dark: #0f172a; --text-muted: #475569; }
* { box-sizing: border-box; }
body { font-family: 'Inter', sans-serif; background-color: var(--paper-bg); color: var(--text-dark); line-height: 1.8; margin: 0; }
.navbar { position: sticky; top: 0; background: rgba(250, 249, 246, 0.98); backdrop-filter: blur(10px); display: flex; justify-content: space-between; padding: 20px 8%; border-bottom: 1px solid rgba(6,78,59,0.1); z-index: 1000; }
.brand { font-family: 'Playfair Display', serif; font-size: 24px; font-weight: 700; color: var(--emerald-main); text-decoration: none; }
.nav-links { display: flex; gap: 30px; }
.nav-links a { text-decoration: none; color: var(--text-muted); font-weight: 600; font-size: 14px; text-transform: uppercase; }
.nav-links a.active { color: var(--emerald-main); border-bottom: 2px solid var(--emerald-light); }
.container { max-width: 900px; margin: 60px auto; padding: 0 40px; }
h1 { font-family: 'Playfair Display', serif; font-size: 48px; color: var(--emerald-main); }
h2 { color: var(--emerald-main); margin-top: 50px; border-bottom: 2px solid var(--emerald-light); padding-bottom: 10px; }
h3 { color: var(--emerald-dark); margin-top: 30px; }
p { margin-bottom: 25px; text-align: justify; font-size: 17px; }
.highlight-box { background: #f0f6f3; padding: 30px; border-radius: 12px; border-left: 6px solid var(--emerald-light); margin: 30px 0; }
footer { text-align: center; padding: 50px; color: var(--text-muted); border-top: 1px solid #ddd; }
CSS_EOF

# 2. 首页 (index.html)
cat << 'HTML_EOF' > index.html
<!DOCTYPE html>
<html>
<head><title>Eco-Legacy | Research Portal</title><link rel="stylesheet" href="css/style.css"></head>
<body>
    <nav class="navbar"><a href="index.html" class="brand">ECO-LEGACY</a><div class="nav-links"><a href="index.html" class="active">Home</a><a href="indus.html">Indus Valley</a><a href="egypt.html">Ancient Egypt</a><a href="greece.html">Ancient Greece</a><a href="singapore.html">Singapore 2030</a></div></nav>
    <div class="container">
        <h1>Echoes of Antiquity</h1>
        <p>Welcome to this digital archive. As a Primary 6 Social Studies project, this portal aims to dissect the intricate relationship between ancient civilization engineering and modern sustainability targets.</p>
        <div class="highlight-box">
            <h3>Project Thesis</h3>
            <p>We hypothesize that the principles of "passive resilience" utilized by the Indus Valley, Egyptian, and Greek civilizations—specifically thermodynamic control, hydraulic management, and solar urbanism—are not merely historical artifacts. Instead, they provide a blueprint for addressing the contemporary "Urban Heat Island" effect and water security challenges faced by Singapore in 2030.</p>
        </div>
        <p>This site contains four in-depth research modules exploring these historical precedents and their modern applications. Each section is a deep dive into the engineering logic that allowed these societies to flourish sustainably for millennia.</p>
    </div>
    <footer>&copy; 2026 Made by Eric.</footer>
</body>
</html>
HTML_EOF

# 3. 印度河流域 (indus.html - 扩充内容)
cat << 'HTML_EOF' > indus.html
<!DOCTYPE html>
<html>
<head><title>Indus Valley | Engineering</title><link rel="stylesheet" href="css/style.css"></head>
<body>
    <nav class="navbar"><a href="index.html" class="brand">ECO-LEGACY</a><div class="nav-links"><a href="index.html">Home</a><a href="indus.html" class="active">Indus Valley</a><a href="egypt.html">Ancient Egypt</a><a href="greece.html">Ancient Greece</a><a href="singapore.html">Singapore 2030</a></div></nav>
    <div class="container">
        <h1>I. The Indus Valley Civilisation</h1>
        <h2>Urban Planning and Thermodynamic Efficiency</h2>
        <p>The Indus Valley Civilisation (c. 2600–1900 BCE) achieved an urban planning precision that was not replicated until the Industrial Revolution. Their cities, including Mohenjo-Daro and Harappa, were built upon a rigid, cardinal grid system that fundamentally altered the thermodynamic profile of the urban environment.</p>
        <h3>Passive Cooling and Wind Corridors</h3>
        <p>The cardinal grid was not purely for aesthetic order; it was a deliberate climate-responsive engineering strategy. By orienting major arteries according to the prevailing wind directions, Harappan engineers created natural "wind tunnels." These streets acted as convective pathways that flushed out heat generated by high-density residential occupation. As air flowed through these narrower streets, the Venturi effect accelerated air speed, effectively cooling the micro-environment.</p>
        <h3>Structural Thermal Lag</h3>
        <p>The Harappans pioneered the use of kiln-fired bricks with a standard 1:2:4 ratio. This mass-produced, standardized material provided incredible thermal inertia. During the day, the thick, heat-absorbent walls of the residential structures absorbed incident solar radiation. This delayed the heat transfer into the interior space (thermal lag). By the time the heat would have penetrated the interior, the sun had set, and the cooler night air began to cool the walls. This natural cycle maintained stable indoor temperatures without energy consumption.</p>
        <h3>Sanitation and Public Welfare</h3>
        <p>While often overlooked, the Indus sanitation system was the most advanced in the ancient world. Their sophisticated drainage system featured covered sewers, manholes, and soak pits to prevent contamination. This focus on public health enabled high-density living without the common plagues that devastated other contemporary civilisations.</p>
    </div>
    <footer>&copy; 2026 Made by Eric.</footer>
</body>
</html>
HTML_EOF

# 4. 古埃及 (egypt.html - 扩充内容)
cat << 'HTML_EOF' > egypt.html
<!DOCTYPE html>
<html>
<head><title>Ancient Egypt | Hydrology</title><link rel="stylesheet" href="css/style.css"></head>
<body>
    <nav class="navbar"><a href="index.html" class="brand">ECO-LEGACY</a><div class="nav-links"><a href="index.html">Home</a><a href="indus.html">Indus Valley</a><a href="egypt.html" class="active">Ancient Egypt</a><a href="greece.html">Ancient Greece</a><a href="singapore.html">Singapore 2030</a></div></nav>
    <div class="container">
        <h1>II. Ancient Egyptian Civilisation</h1>
        <h2>Hydraulic Stewardship and Basin Management</h2>
        <p>The agricultural backbone of Ancient Egypt was not the subversion of the Nile, but the harmonious integration of engineering with its seasonal flood cycle. The Egyptian approach to sustainability serves as a definitive case study in circular water management.</p>
        <h3>The Basin Irrigation Network</h3>
        <p>Egyptian engineers developed a "basin irrigation" network. Instead of draining water away, they used earthen dikes to create shallow, manageable floodplains. When the Nile flooded, these basins were filled, allowing the water to stand for weeks. This served two critical purposes: first, it ensured deep soil hydration; second, it allowed the rich, mineral-heavy silt carried by the Nile to settle on the land, providing a natural fertilizer that eliminated the need for modern chemicals.</p>
        <h3>The Nilometer: Data Governance</h3>
        <p>The Nile's behavior was unpredictable, and the Egyptian state responded with data-driven governance. The Nilometer—a stone column or well calibrated to the river level—was the state’s primary instrument for resource management. By measuring the flood height, the state could forecast grain yields and set tax rates. This was arguably the world’s first "Big Data" approach to national resource planning.</p>
        <h3>Technological Innovation: The Shaduf</h3>
        <p>To irrigate lands higher than the flood level, the Egyptians invented the Shaduf—a counterweighted lever system. This simple machine, utilizing a fulcrum and a weight, allowed a single operator to lift water with minimal caloric expenditure. It was a perfect marriage of physics and agricultural necessity.</p>
    </div>
    <footer>&copy; 2026 Made by Eric.</footer>
</body>
</html>
HTML_EOF

# 5. 古希腊 (greece.html - 扩充内容)
cat << 'HTML_EOF' > greece.html
<!DOCTYPE html>
<html>
<head><title>Ancient Greece | Kinetic Energy</title><link rel="stylesheet" href="css/style.css"></head>
<body>
    <nav class="navbar"><a href="index.html" class="brand">ECO-LEGACY</a><div class="nav-links"><a href="index.html">Home</a><a href="indus.html">Indus Valley</a><a href="egypt.html">Ancient Egypt</a><a href="greece.html" class="active">Ancient Greece</a><a href="singapore.html">Singapore 2030</a></div></nav>
    <div class="container">
        <h1>III. Ancient Greek Engineering</h1>
        <h2>Kinetic Leverage and Socratic Solar Planning</h2>
        <p>Ancient Greek civilisations shifted the focus from static infrastructure to the application of mechanical force and urban geometry. Their innovations in kinetic energy and passive solar architecture demonstrate an early mastery of renewable energy.</p>
        <h3>Kinetic Energy and Mechanical Advantage</h3>
        <p>The Greeks were masters of the gear. Their development of the vertical waterwheel, utilized in milling processes, allowed for the processing of grain at a scale far beyond human labor capacity. By converting the kinetic energy of flowing water into rotational force via gear transmission, they achieved a massive "mechanical advantage." This reduced the energy cost of food production and demonstrated that mechanical assistance could allow a population to grow without over-exploiting manual labor forces.</p>
        <h3>The Olynthus Grid and Solar Thermal Design</h3>
        <p>Greek architects were the first to formalize "passive solar" house design. At the city of Olynthus, urban planning regulations mandated that the main rooms of every house face South. This specific orientation allowed the low-angled winter sun to penetrate deep into the home, providing heat during colder months, while the high-angled summer sun was blocked by roof overhangs (eaves), keeping the house cool. This was a sophisticated application of geometry to regulate indoor climate—a principle we now call "Solar Thermal Design."</p>
    </div>
    <footer>&copy; 2026 Made by Eric.</footer>
</body>
</html>
HTML_EOF

# 6. 新加坡 2030 (singapore.html - 扩充内容)
cat << 'HTML_EOF' > singapore.html
<!DOCTYPE html>
<html>
<head><title>Singapore 2030 | Strategy</title><link rel="stylesheet" href="css/style.css"></head>
<body>
    <nav class="navbar"><a href="index.html" class="brand">ECO-LEGACY</a><div class="nav-links"><a href="index.html">Home</a><a href="indus.html">Indus Valley</a><a href="egypt.html">Ancient Egypt</a><a href="greece.html">Ancient Greece</a><a href="singapore.html" class="active">Singapore 2030</a></div></nav>
    <div class="container">
        <h1>IV. Singapore Green Plan 2030</h1>
        <h2>Synthesizing Ancient Wisdom for Modern Resilience</h2>
        <p>Singapore’s 2030 sustainability goals are ambitious, focusing on energy resetting, resilient future-proofing, and green living. By applying the "Ancient Toolkit" analyzed in previous sections, we can synthesize a high-tech resilience strategy.</p>
        <h3>1. The "Tengah" Model: Harappan Wind Corridors</h3>
        <p>Tengah Town is a prime candidate for implementing the Indus Valley's cardinal wind-corridor logic. By simulating the city's building layout through Computational Fluid Dynamics (CFD), we can optimize HDB blocks to funnel tropical winds across the estate, reducing the ambient temperature without needing extra air-conditioning load.</p>
        <h3>2. Managing Urban Water: The Modern Nilometer</h3>
        <p>Singapore’s Marina Barrage is the 21st-century evolution of the Nilometer. It uses advanced sensor networks to manage the reservoir levels against tidal and weather fluctuations. By integrating "basin-like" rain gardens into our urban fabric (the ABC Waters programme), we are mirroring the Egyptian silt-retention and water-filtration systems to manage storm runoff effectively.</p>
        <h3>3. Photovoltaic Optimization: Socratic Geometry</h3>
        <p>To reach the 2 GWp solar energy target, we must apply the Greek "Olynthus" principle. This means not just putting solar panels on roofs, but integrating them into the facade of buildings at specific angles determined by solar-tracking geometry to maximize light capture regardless of the sun's position. This "Socratic Urbanism" ensures that every square meter of urban surface is optimized for renewable harvest.</p>
    </div>
    <footer>&copy; 2026 Made by Eric.</footer>
</body>
</html>
HTML_EOF

echo "✅ Build complete! All pages generated with deep academic content."
EOF

# 运行脚本
chmod +x build_eric_site.sh
./build_eric_site.sh